# Generated by Django 4.2 on 2023-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=60, unique=True)),
                ('definition_id', models.CharField(max_length=60, unique=True)),
                ('scans', models.CharField(max_length=60, unique=True)),
                ('url', models.URLField(max_length=300)),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=60)),
            ],
        ),
    ]
